services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: npm run start:dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: db
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  pgdata:
